const reviews = [
    { author: 'Jhonbrix Maat', date: 'Mar 10 2024', title: 'Serves Its Purpose Well', comment: 'The product exceeded my expectations. It\'s not just good, it\'s fantastic! I\'ve been using it for a while now and it still performs flawlessly. Highly recommended.' },
    { author: 'Joshua Matias', date: 'Mar 11 2024', title: 'Good Enough', comment: 'At first, I was hesitant to buy this product, but I\'m so glad I did. It has completely changed the way I work. It\'s efficient, reliable, and durable. I couldn\'t ask for more!' },
    { author: 'Kristhan Aguilar', date: 'Mar 12 2024', title: 'Meets Basic Needs', comment: 'I\'ve tried many similar products in the past, but none of them compare to this one. The quality is top-notch, the design is sleek, and the performance is outstanding. I\'m extremely satisfied with my purchase.' },
    { author: 'Lenard Gaa', date: 'Mar 13 2024', title: 'Works As Expected', comment: 'This product is a game-changer. It\'s not just a convenience, it\'s a necessity. I use it every day and it never fails to impress me. If you\'re on the fence about buying it, don\'t hesitate. You won\'t regret it!' },
    { author: 'Lyle Ramales', date: 'Mar 14 2024', title: 'Acceptable Performance', comment: 'I\'ve been searching for the perfect product for a long time, and I finally found it. This product is everything I\'ve ever wanted and more. It\'s versatile, user-friendly, and built to last. I couldn\'t be happier with my purchase.' },
    { author: 'Michael Jay Bagacina', date: 'Mar 15 2024', title: 'Decent Product', comment: 'Words cannot describe how much I love this product. It\'s like it was made just for me. It\'s intuitive, efficient, and incredibly effective. I can\'t imagine my life without it now.' },
    { author: 'Jobert Niebres', date: 'Mar 01 2024', title: 'Gets the Job Done', comment: 'I was skeptical about buying this product at first, but now I can\'t imagine my life without it. It\'s become an essential part of my daily routine. It\'s reliable, durable, and worth every penny.' },
    { author: 'Rommel Barbonio', date: 'Mar 17 2024', title: 'Decent for the Price', comment: 'I\'ve been using this product for a while now, and it\'s never let me down. It\'s reliable, durable, and performs flawlessly every time. I would highly recommend it to anyone in need of a quality product.' },
    { author: 'Shann Arlly Lagdaan', date: 'Mar 18 2024', title: 'Meets Expectations', comment: 'I\'m extremely impressed with this product. It\'s exceeded all of my expectations and then some. It\'s intuitive, efficient, and built to last. I couldn\'t be happier with my purchase.' },
    { author: 'Vincent Anthony Hermoso Moreno', date: 'Mar 19 2024', title: 'Fulfills Needs', comment: 'This product is a game-changer. It\'s revolutionized the way I work. It\'s reliable, efficient, and incredibly user-friendly. I would recommend it to anyone looking to streamline their workflow.' },
];
export default reviews;